server:
  port: 8888
logger:
  toggle: true
  serviceUri: test

logging:
    level:
      root: 'info'

# Datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root