server:
  port: 8181
logger:
  toggle: true
  serviceUri: test

logging:
    level:
      root: 'info'

# Datasource
spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/base
    url: jdbc:postgresql://altusdb.cepousbd7jvv.ap-southeast-1.rds.amazonaws.com:5432/base
    username: altusDev
    password: QwertY123!